name: Scan for Secrets with TruffleHog
 
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  scan-secrets:
    runs-on: [self-hosted, linux]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Activate existing virtual environment
        run: |
          source /home/sarthak.magar/trufflehog/myenv/bin/activate  # Path to your existing virtual environment

      - name: Run TruffleHog for secrets scan
        run: |
          # Use Personal Access Token (PAT) for authentication
          git_url="https://github.com/${{ github.repository }}.git"
          git_url_with_token="https://${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }}.git"
          
          # Run TruffleHog with the token-based Git URL
          trufflehog --json $git_url_with_token > trufflehog_output.json

      - name: Check if secrets are found and create an issue
        id: create-issue
        run: |
          secrets_found=$(cat trufflehog_output.json | jq 'length')
          
          if [ "$secrets_found" -gt 0 ]; then
            echo "Secrets found. Creating an issue..."
            
            # Create an issue using GitHub API if secrets were found
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -d '{
                    "title": "Secrets Found in Repository",
                    "body": "TruffleHog has detected potential secrets in this repository. Please review the scan results.",
                    "labels": ["security", "secrets"]
                  }' \
              https://api.github.com/repos/${{ github.repository }}/issues
          else
            echo "No secrets found."
          fi
